package:
  name: "qteasy"
  version: "1.2.3"

source:
  git_rev: v1.2.3
  git_url: https://github.com/shepherdpp/qteasy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas>=1.1.0
    - numpy>=1.18.1
    - numba>=0.47.0
    - tushare>=1.2.89
    - mplfinance
    - rich>=10.0.0
    - textual

about:
  home: https://github.com/shepherdpp/qteasy
  license: BSD 3-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "A fast quantitative investment tool kit"

extra:
  recipe-maintainers:
    - shepherdpp