package:
  name: "qteasy"
  version: "1.0.23"

source:
  git_rev: v1.0.23
  git_url: https://github.com/shepherdpp/qteasy

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas>=1.1.0, <=1.5.3
    - numpy>=1.18.1, <=1.21.5
    - numba>=0.47.0, <=0.56.4
    - tushare>=1.2.89
    - mplfinance>=0.11
    - rich>=10.0.0
    - urllib3>=1.25.8, <=1.26.7

about:
  home: https://github.com/shepherdpp/qteasy
  license: BSD 3-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "A fast quantitative investment tool kit"

extra:
  recipe-maintainers:
    - shepherdpp